# Generated by Django 2.2.4 on 2020-03-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retirecenterapp', '0002_auto_20200307_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptBuilding', models.CharField(max_length=50)),
                ('aptRoomNum', models.IntegerField(max_length=5)),
                ('aptFloor', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordDescription', models.TextField()),
                ('creationDate', models.DateField()),
                ('ordPriority', models.CharField(choices=[('seva', 'High'), ('sevb', 'Medium'), ('sevc', 'Low')], default='sevc', max_length=50)),
                ('ordStatus', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('inprog', 'In Progress'), ('closed', 'Closed')], default='new', max_length=50)),
                ('ordProbType', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('appliance', 'Appliance'), ('other', 'Other')], max_length=50)),
                ('aptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirecenterapp.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commDate', models.DateField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirecenterapp.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirecenterapp.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Apt_Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('AptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirecenterapp.Apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
