# Generated by Django 2.2.4 on 2020-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirecenterapp', '0004_auto_20200307_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('maint', 'Maintenance'), ('staff', 'Staff'), ('resident', 'Resident')], max_length=254),
        ),
    ]
