# Generated by Django 2.2.4 on 2020-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirecenterapp', '0005_auto_20200307_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
