# Generated by Django 2.2.4 on 2020-03-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirecenterapp', '0007_auto_20200310_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creationDate',
            new_name='created_date',
        ),
    ]
