# Generated by Django 2.2.4 on 2020-03-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirecenterapp', '0008_auto_20200310_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordPriority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordProbType',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Appliance', 'Appliance'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordStatus',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='New', max_length=50),
        ),
    ]
